# DATA
spring.datasource.url=jdbc:mysql://localhost:3306/university-uat?createDatabaseIfNotExist=true
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:sql/schema/test-schema.sql
spring.sql.init.data-locations=classpath:sql/data/test-data.sql
spring.datasource.username=root
spring.datasource.password=
