# DATA
spring.datasource.url=jdbc:mysql://localhost:3306/bookshop?createDatabaseIfNotExist=true
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:sql/schema/prod-schema.sql
# To not initialize the database on start, replace
# the 3 lines above with the 2 following lines:
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.sql.init.mode=never
spring.datasource.username=root
spring.datasource.password=password
